package com.adrec.service

import com.google.api.client.googleapis.javanet.GoogleNetHttpTransport
import com.google.api.client.json.gson.GsonFactory
import com.google.api.services.youtube.YouTube
import com.google.api.services.youtube.model.*
import com.google.auth.http.HttpCredentialsAdapter
import com.google.auth.oauth2.GoogleCredentials
import com.google.auth.oauth2.UserCredentials
import org.slf4j.LoggerFactory

class YouTubeService(
    private val clientId: String,
    private val clientSecret: String,
    private val refreshToken: String,
) {
    private val log = LoggerFactory.getLogger(YouTubeService::class.java)

    private fun buildYouTube(): YouTube {
        val credentials = UserCredentials.newBuilder()
            .setClientId(clientId)
            .setClientSecret(clientSecret)
            .setRefreshToken(refreshToken)
            .build()

        return YouTube.Builder(
            GoogleNetHttpTransport.newTrustedTransport(),
            GsonFactory.getDefaultInstance(),
            HttpCredentialsAdapter(credentials),
        )
            .setApplicationName("adrec")
            .build()
    }

    fun createPlaylist(title: String, videoIds: List<String>): Pair<String, String> {
        val yt = buildYouTube()

        val playlist = yt.playlists()
            .insert(
                listOf("snippet", "status"),
                Playlist().apply {
                    snippet = PlaylistSnippet().apply {
                        this.title = title
                        description = "Generated by AdRec"
                    }
                    status = PlaylistStatus().apply {
                        privacyStatus = "unlisted"
                    }
                },
            )
            .execute()

        val playlistId = playlist.id
        log.info("Created YouTube playlist: $playlistId")

        val uniqueVideoIds = videoIds.distinct()
        uniqueVideoIds.forEachIndexed { index, videoId ->
            try {
                yt.playlistItems()
                    .insert(
                        listOf("snippet"),
                        PlaylistItem().apply {
                            snippet = PlaylistItemSnippet().apply {
                                this.playlistId = playlistId
                                resourceId = ResourceId().apply {
                                    kind = "youtube#video"
                                    this.videoId = videoId
                                }
                                position = index.toLong()
                            }
                        },
                    )
                    .execute()
            } catch (e: Exception) {
                log.warn("Failed to add video $videoId to playlist $playlistId: ${e.message}")
            }
        }

        val playlistUrl = "https://www.youtube.com/playlist?list=$playlistId"
        return Pair(playlistId, playlistUrl)
    }
}
